### ISSUE TITLE
关于数据格式

### ISSUE THREAD

**Issue by kevinbro96** [Pealing/DDAN#1]
请问按照您的读取数据的代码，训练数据和测试数据的存储目录和图片命名规则应该是什么样的？

**Comment by PeixianChen** [comment]
Train datasets: DG/\*/bounding_box_train/\*.jpg(png..)
Test datasets: DG/\*/query_test(gallery_test)/\*.jpg(png...)

**Comment by kevinbro96** [comment]
样本的名称呢？ 请问是id_cid吗？比如322_c5就是第五个camera，行人id为322

**Comment by Pealing** [comment]
是的

**Comment by PeixianChen** [comment]
> 样本的名称呢？ 请问是id_cid吗？比如322_c5就是第五个camera，行人id为322

是的

**Comment by kevinbro96** [comment]
请问您能把您的测试数据发给我一下吗？每个测试数据集处理起来都不一样，非常麻烦。
如果您能发给我的话，将对我非常有帮助！我的邮箱是kwyang@mail.ustc.edu.cn，麻烦您了！

**Comment by PeixianChen** [comment]
> 请问您能把您的测试数据发给我一下吗？每个测试数据集处理起来都不一样，非常麻烦。
> 如果您能发给我的话，将对我非常有帮助！我的邮箱是[kwyang@mail.ustc.edu.cn](mailto:kwyang@mail.ustc.edu.cn)，麻烦您了！

数据集数量较多，请从相应官网下载，我只对图片名按照上述的格式进行了批量修改。
感谢您的关注，后续会将这一问题在README中说明。

**Comment by liqilei** [comment]
please can you provide the scripts for formating the datasets?
